pub const ASCII_ART: &[&str] = &[
    r"                                   /\",
    r"                              /\  //\\",
    r"                       /\    //\\///\\\        /\",
    r"                      //\\  ///\////\\\\  /\  //\\",
    r"         /\          /  ^ \/^ ^/^  ^  ^ \/^ \/  ^ \",
    r"        / ^\    /\  / ^   /  ^/ ^ ^ ^   ^\ ^/  ^^  \",
    r"       /^   \  / ^\/ ^ ^   ^ / ^  ^    ^  \/ ^   ^  \       *",
    r"      /  ^ ^ \/^  ^\ ^ ^ ^   ^  ^   ^   ____  ^   ^  \     /|\",
    r"     / ^ ^  ^ \ ^  _\___________________|  |_____^ ^  \   /||o\",
    r"    / ^^  ^ ^ ^\  /______________________________\ ^ ^ \ /|o|||\",
    r"   /  ^  ^^ ^ ^  /________________________________\  ^  /|||||o|\",
    r"  /^ ^  ^ ^^  ^    ||___|___||||||||||||___|__|||      /||o||||||\",
    r" / ^   ^   ^    ^  ||___|___||||||||||||___|__|||          | |",
    r"/ ^ ^ ^  ^  ^  ^   ||||||||||||||||||||||||||||||oooooooooo| |ooooooo",
    r"ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
];

pub const DISTRACTION_PHRASES: &[&str] = &[
    "Brillando",
    "Zumbando",
    "Revoloteando",
    "Saltando",
    "Flotando",
    "Destellando",
    "Chapoteando",
    "Sonriendo",
    "Resplandeciendo",
    "Canturreando",
    "Dançando",
    "Girando",
    "Burbujeando",
    "Crepitando",
    "Pintando",
    "Tejiendo",
    "Explorando",
    "Saltimbanqueando",
    "Chapurreando",
    "Lumineando",
    "Zarandeando",
    "Tintineando",
    "Rebotando",
    "Culebreando",
    "Espiraleando",
    "Saltarínando",
    "Voloteando",
    "Susurrando",
    "Chispeando",
    "Danilando",
    "Burbujeleteando",
    "Prismando",
    "Meneoando",
    "Brincolineando",
    "Planteando",
    "Revolineando",
    "Sonorineando",
    "Floreando",
    "Risueñeando",
    "Lumineleando",
    "Carcajeando",
    "Tintoreando",
    "Brillulineando",
    "Zumbileando",
    "Espumando",
    "Chapoteleando",
    "Vuelineando",
    "Trinando",
    "Susurrileando",
    "Ventileando",
];

pub const WAVE_FRAMES: &[&str] = &[
    "≈   ≈   ≈   ≈   ≈   ≈   ≈",
    " ≈   ≈   ≈   ≈   ≈   ≈   ",
    "  ≈   ≈   ≈   ≈   ≈   ≈  ",
    "   ≈   ≈   ≈   ≈   ≈   ≈ ",
    "  ≈   ≈   ≈   ≈   ≈   ≈  ",
    " ≈   ≈   ≈   ≈   ≈   ≈   ",
];
